In [1]:
import pandas as pd

In [2]:
test_1 = pd.read_csv('../data_padel/padel_player_dataset_001.csv')
test_2 = pd.read_csv('../data_padel/padel_player_dataset_002.csv')
test_3 = pd.read_csv('../data_padel/padel_player_dataset_003.csv')
test_4 = pd.read_csv('../data_padel/padel_player_dataset_004.csv')
test_5 = pd.read_csv('../data_padel/padel_player_dataset_005.csv')
test_6 = pd.read_csv('../data_padel/padel_player_dataset_006.csv')
test_7 = pd.read_csv('../data_padel/padel_player_dataset_007.csv')
test_8 = pd.read_csv('../data_padel/padel_player_dataset_008.csv')
test_9 = pd.read_csv('../data_padel/padel_player_dataset_009.csv')
test_10 = pd.read_csv('../data_padel/padel_player_dataset_010.csv')
test_11 = pd.read_csv('../data_padel/padel_player_dataset_011.csv')
test_12 = pd.read_csv('../data_padel/padel_player_dataset_012.csv')
test_13 = pd.read_csv('../data_padel/padel_player_dataset_013.csv')
test_14 = pd.read_csv('../data_padel/padel_player_dataset_014.csv')
test_15 = pd.read_csv('../data_padel/padel_player_dataset_015.csv')
test_16 = pd.read_csv('../data_padel/padel_player_dataset_016.csv')
test_17 = pd.read_csv('../data_padel/padel_player_dataset_017.csv')
test_18 = pd.read_csv('../data_padel/padel_player_dataset_018.csv')
test_19 = pd.read_csv('../data_padel/padel_player_dataset_019.csv')
test_20 = pd.read_csv('../data_padel/padel_player_dataset_020.csv')

In [3]:
import pandas as pd

# Lista para almacenar los DataFrames de cada archivo CSV
dfs = []

# Iterar sobre todos los archivos CSV
for i in range(1, 21):
    # Construir la ruta al archivo CSV
    ruta_archivo = f'../data_padel/padel_player_dataset_{i:03}.csv'
    
    # Leer el archivo CSV y agregarlo al DataFrame
    df = pd.read_csv(ruta_archivo)
    dfs.append(df)

# Concatenar todos los DataFrames en uno solo
test = pd.concat(dfs, ignore_index=True)

In [4]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 20 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Player ID                              20000 non-null  int64
 1   Age Group                              20000 non-null  object
 2   Gender                                 20000 non-null  object
 3   Skill Level                            20000 non-null  object
 4   Errores No Forzados                    20000 non-null  int64
 5   Winners                                20000 non-null  int64
 6   Puntos Ganados de Remate               20000 non-null  int64
 7   % Primeros Saques                      20000 non-null  int64
 8   % Segundos Saques                      20000 non-null  int64
 9   % Puntos Ganados con Primeros Saques   20000 non-null  int64
 10  % Puntos Ganados con Segundos Saques   20000 non-null  int64
 11  Dobles Faltas                          20000 non-null  int64
 12  Km Recorridos                          20000 non-null  int64
 13  Zonas de Calor                         20000 non-null  object
 14  Puntos de Break                        20000 non-null  int64
 15  Puntos de Oro                          20000 non-null  int64
 16  Errores No Forzados de Fondo de Pista  20000 non-null  int64
 17  Errores No Forzados en Red             20000 non-null  int64
 18  % de Restos Fallados                   20000 non-null  int64
 19  Posición Preferente                    20000 non-null  object
dtypes: int64(15), object(5)
memory usage: 3.1+ MB

In [5]:
# Aquí asumimos que 'df' es el DataFrame resultante de la concatenación de los CSV

# Crear una columna 'Partido' con números consecutivos para cada grupo de ID
test['Partido'] = test.groupby('Player ID').cumcount() + 1

In [6]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 21 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Player ID                              20000 non-null  int64
 1   Age Group                              20000 non-null  object
 2   Gender                                 20000 non-null  object
 3   Skill Level                            20000 non-null  object
 4   Errores No Forzados                    20000 non-null  int64
 5   Winners                                20000 non-null  int64
 6   Puntos Ganados de Remate               20000 non-null  int64
 7   % Primeros Saques                      20000 non-null  int64
 8   % Segundos Saques                      20000 non-null  int64
 9   % Puntos Ganados con Primeros Saques   20000 non-null  int64
 10  % Puntos Ganados con Segundos Saques   20000 non-null  int64
 11  Dobles Faltas                          20000 non-null  int64
 12  Km Recorridos                          20000 non-null  int64
 13  Zonas de Calor                         20000 non-null  object
 14  Puntos de Break                        20000 non-null  int64
 15  Puntos de Oro                          20000 non-null  int64
 16  Errores No Forzados de Fondo de Pista  20000 non-null  int64
 17  Errores No Forzados en Red             20000 non-null  int64
 18  % de Restos Fallados                   20000 non-null  int64
 19  Posición Preferente                    20000 non-null  object
 20  Partido                                20000 non-null  int64
dtypes: int64(16), object(5)
memory usage: 3.2+ MB

In [7]:
filas = test.iloc[[0, 1000, 2000, 3000]]
filas
# Mostrar las filas seleccionadas

,Player ID,Age Group,Gender,Skill Level,Errores No Forzados,Winners,Puntos Ganados de Remate,% Primeros Saques,% Segundos Saques,% Puntos Ganados con Primeros Saques,...,Dobles Faltas,Km Recorridos,Zonas de Calor,Puntos de Break,Puntos de Oro,Errores No Forzados de Fondo de Pista,Errores No Forzados en Red,% de Restos Fallados,Posición Preferente,Partido
0,1,46-60,Female,Advanced,48,16,13,0,79,20,...,7,2,C,13,32,18,19,6,D,1
1000,1,<18,Male,Intermediate,16,24,4,86,77,87,...,9,1,B,18,26,5,9,16,R,2
2000,1,31-45,Female,Beginner,32,27,0,100,38,17,...,5,0,A,10,8,16,18,4,R,3
3000,1,18-30,Male,Beginner,16,25,18,92,82,41,...,3,4,C,1,24,11,8,23,D,4

In [8]:
test = test.drop(columns=['Skill Level'], axis = 1)

In [13]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 19 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Player ID                              20000 non-null  int64
 1   Gender                                 20000 non-null  object
 2   Errores No Forzados                    20000 non-null  int64
 3   Winners                                20000 non-null  int64
 4   Puntos Ganados de Remate               20000 non-null  int64
 5   % Primeros Saques                      20000 non-null  int64
 6   % Segundos Saques                      20000 non-null  int64
 7   % Puntos Ganados con Primeros Saques   20000 non-null  int64
 8   % Puntos Ganados con Segundos Saques   20000 non-null  int64
 9   Dobles Faltas                          20000 non-null  int64
 10  Km Recorridos                          20000 non-null  int64
 11  Zonas de Calor                         20000 non-null  object
 12  Puntos de Break                        20000 non-null  int64
 13  Puntos de Oro                          20000 non-null  int64
 14  Errores No Forzados de Fondo de Pista  20000 non-null  int64
 15  Errores No Forzados en Red             20000 non-null  int64
 16  % de Restos Fallados                   20000 non-null  int64
 17  Posición Preferente                    20000 non-null  object
 18  Partido                                20000 non-null  int64
dtypes: int64(16), object(3)
memory usage: 2.9+ MB

In [12]:
test = test.drop(columns=['Age Group'], axis = 1)

KeyError: "['Age Group'] not found in axis"

In [14]:
test.head()

,Player ID,Gender,Errores No Forzados,Winners,Puntos Ganados de Remate,% Primeros Saques,% Segundos Saques,% Puntos Ganados con Primeros Saques,% Puntos Ganados con Segundos Saques,Dobles Faltas,Km Recorridos,Zonas de Calor,Puntos de Break,Puntos de Oro,Errores No Forzados de Fondo de Pista,Errores No Forzados en Red,% de Restos Fallados,Posición Preferente,Partido
0,1,Female,48,16,13,0,79,20,86,7,2,C,13,32,18,19,6,D,1
1,2,Female,29,25,4,88,71,71,92,8,4,B,6,35,47,20,19,R,1
2,3,Female,44,28,10,65,55,20,4,9,0,B,14,32,21,9,23,D,1
3,4,Female,5,25,15,29,88,10,41,1,4,C,15,30,48,8,23,R,1
4,5,Female,16,17,1,2,49,37,6,8,3,A,18,20,14,4,22,D,1

In [16]:
unique_player_ids = test['Player ID'].unique()
print(unique_player_ids)

[   1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25   26   27   28
   29   30   31   32   33   34   35   36   37   38   39   40   41   42
   43   44   45   46   47   48   49   50   51   52   53   54   55   56
   57   58   59   60   61   62   63   64   65   66   67   68   69   70
   71   72   73   74   75   76   77   78   79   80   81   82   83   84
   85   86   87   88   89   90   91   92   93   94   95   96   97   98
   99  100  101  102  103  104  105  106  107  108  109  110  111  112
  113  114  115  116  117  118  119  120  121  122  123  124  125  126
  127  128  129  130  131  132  133  134  135  136  137  138  139  140
  141  142  143  144  145  146  147  148  149  150  151  152  153  154
  155  156  157  158  159  160  161  162  163  164  165  166  167  168
  169  170  171  172  173  174  175  176  177  178  179  180  181  182
  183  184  185  186  187  188  189  190  191  192  193  194  195  196
  197  198  199  200  201  202  203  204  205  206  207  208  209  210
  211  212  213  214  215  216  217  218  219  220  221  222  223  224
  225  226  227  228  229  230  231  232  233  234  235  236  237  238
  239  240  241  242  243  244  245  246  247  248  249  250  251  252
  253  254  255  256  257  258  259  260  261  262  263  264  265  266
  267  268  269  270  271  272  273  274  275  276  277  278  279  280
  281  282  283  284  285  286  287  288  289  290  291  292  293  294
  295  296  297  298  299  300  301  302  303  304  305  306  307  308
  309  310  311  312  313  314  315  316  317  318  319  320  321  322
  323  324  325  326  327  328  329  330  331  332  333  334  335  336
  337  338  339  340  341  342  343  344  345  346  347  348  349  350
  351  352  353  354  355  356  357  358  359  360  361  362  363  364
  365  366  367  368  369  370  371  372  373  374  375  376  377  378
  379  380  381  382  383  384  385  386  387  388  389  390  391  392
  393  394  395  396  397  398  399  400  401  402  403  404  405  406
  407  408  409  410  411  412  413  414  415  416  417  418  419  420
  421  422  423  424  425  426  427  428  429  430  431  432  433  434
  435  436  437  438  439  440  441  442  443  444  445  446  447  448
  449  450  451  452  453  454  455  456  457  458  459  460  461  462
  463  464  465  466  467  468  469  470  471  472  473  474  475  476
  477  478  479  480  481  482  483  484  485  486  487  488  489  490
  491  492  493  494  495  496  497  498  499  500  501  502  503  504
  505  506  507  508  509  510  511  512  513  514  515  516  517  518
  519  520  521  522  523  524  525  526  527  528  529  530  531  532
  533  534  535  536  537  538  539  540  541  542  543  544  545  546
  547  548  549  550  551  552  553  554  555  556  557  558  559  560
  561  562  563  564  565  566  567  568  569  570  571  572  573  574
  575  576  577  578  579  580  581  582  583  584  585  586  587  588
  589  590  591  592  593  594  595  596  597  598  599  600  601  602
  603  604  605  606  607  608  609  610  611  612  613  614  615  616
  617  618  619  620  621  622  623  624  625  626  627  628  629  630
  631  632  633  634  635  636  637  638  639  640  641  642  643  644
  645  646  647  648  649  650  651  652  653  654  655  656  657  658
  659  660  661  662  663  664  665  666  667  668  669  670  671  672
  673  674  675  676  677  678  679  680  681  682  683  684  685  686
  687  688  689  690  691  692  693  694  695  696  697  698  699  700
  701  702  703  704  705  706  707  708  709  710  711  712  713  714
  715  716  717  718  719  720  721  722  723  724  725  726  727  728
  729  730  731  732  733  734  735  736  737  738  739  740  741  742
  743  744  745  746  747  748  749  750  751  752  753  754  755  756
  757  758  759  760  761  762  763  764  765  766  767  768  769  770
  771  772  773  774  775  776  777  778  779  780  781  782  783  784
  785  786  787  788  789  790  791  792  793  794  795  796  797  798
  799  800  801  802  803  804  805  806  807  808  809  810  811  812
  813  814  815  816  817  818  819  820  821  822  823  824  825  826
  827  828  829  830  831  832  833  834  835  836  837  838  839  840
  841  842  843  844  845  846  847  848  849  850  851  852  853  854
  855  856  857  858  859  860  861  862  863  864  865  866  867  868
  869  870  871  872  873  874  875  876  877  878  879  880  881  882
  883  884  885  886  887  888  889  890  891  892  893  894  895  896
  897  898  899  900  901  902  903  904  905  906  907  908  909  910
  911  912  913  914  915  916  917  918  919  920  921  922  923  924
  925  926  927  928  929  930  931  932  933  934  935  936  937  938
  939  940  941  942  943  944  945  946  947  948  949  950  951  952
  953  954  955  956  957  958  959  960  961  962  963  964  965  966
  967  968  969  970  971  972  973  974  975  976  977  978  979  980
  981  982  983  984  985  986  987  988  989  990  991  992  993  994
  995  996  997  998  999 1000]

In [28]:
import numpy as np
import pandas as pd

# Supongamos que tenemos 1000 IDs
total_ids = 1000

# Calculamos la cantidad de grupos de edad
cantidad_grupos_edad = 5  # Cambia esto según tus necesidades

# Dividimos los IDs en grupos de edad
ids_por_grupo = total_ids // cantidad_grupos_edad

# Creamos los rangos de edad
rangos_edad = ['<18', '18-30', '31-45', '46-60', '>60']

# Repetimos los rangos de edad según la cantidad de IDs por grupo
edades = np.repeat(rangos_edad, ids_por_grupo)

# Creamos un DataFrame con los IDs y las edades asignadas
df_edades = pd.DataFrame({'Player ID': range(1, total_ids + 1), 'Edad': edades})

# Visualizamos el resultado
print(df_edades)

     Player ID Edad
0            1  <18
1            2  <18
2            3  <18
3            4  <18
4            5  <18
..         ...  ...
995        996  >60
996        997  >60
997        998  >60
998        999  >60
999       1000  >60

[1000 rows x 2 columns]

In [30]:
merged_df = pd.merge(test, df_edades, on='Player ID', how='inner')

# Mostrar el DataFrame fusionado
merged_df

,Player ID,Gender,Errores No Forzados,Winners,Puntos Ganados de Remate,% Primeros Saques,% Segundos Saques,% Puntos Ganados con Primeros Saques,% Puntos Ganados con Segundos Saques,Dobles Faltas,Km Recorridos,Zonas de Calor,Puntos de Break,Puntos de Oro,Errores No Forzados de Fondo de Pista,Errores No Forzados en Red,% de Restos Fallados,Posición Preferente,Partido,Edad
0,1,Female,48,16,13,0,79,20,86,7,2,C,13,32,18,19,6,D,1,<18
1,2,Female,29,25,4,88,71,71,92,8,4,B,6,35,47,20,19,R,1,<18
2,3,Female,44,28,10,65,55,20,4,9,0,B,14,32,21,9,23,D,1,<18
3,4,Female,5,25,15,29,88,10,41,1,4,C,15,30,48,8,23,R,1,<18
4,5,Female,16,17,1,2,49,37,6,8,3,A,18,20,14,4,22,D,1,<18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,996,Female,27,18,8,100,36,42,46,9,2,B,0,34,9,6,15,D,20,>60
19996,997,Female,42,18,13,44,98,90,55,7,4,A,17,10,9,5,23,D,20,>60
19997,998,Female,38,15,13,74,81,49,66,2,1,B,11,34,13,6,21,R,20,>60
19998,999,Male,15,0,12,66,84,62,1,7,1,C,14,3,17,18,18,D,20,>60
19999,1000,Male,36,13,7,11,24,40,78,4,2,C,1,15,1,3,12,R,20,>60

In [32]:
filas = merged_df.iloc[[0, 1000, 2000, 3000]]
filas

,Player ID,Gender,Errores No Forzados,Winners,Puntos Ganados de Remate,% Primeros Saques,% Segundos Saques,% Puntos Ganados con Primeros Saques,% Puntos Ganados con Segundos Saques,Dobles Faltas,Km Recorridos,Zonas de Calor,Puntos de Break,Puntos de Oro,Errores No Forzados de Fondo de Pista,Errores No Forzados en Red,% de Restos Fallados,Posición Preferente,Partido,Edad
0,1,Female,48,16,13,0,79,20,86,7,2,C,13,32,18,19,6,D,1,<18
1000,1,Male,16,24,4,86,77,87,36,9,1,B,18,26,5,9,16,R,2,<18
2000,1,Female,32,27,0,100,38,17,56,5,0,A,10,8,16,18,4,R,3,<18
3000,1,Male,16,25,18,92,82,41,89,3,4,C,1,24,11,8,23,D,4,<18

In [34]:
merged_df = merged_df.drop(columns=['Gender'], axis = 1)

In [35]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 19 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Player ID                              20000 non-null  int64
 1   Errores No Forzados                    20000 non-null  int64
 2   Winners                                20000 non-null  int64
 3   Puntos Ganados de Remate               20000 non-null  int64
 4   % Primeros Saques                      20000 non-null  int64
 5   % Segundos Saques                      20000 non-null  int64
 6   % Puntos Ganados con Primeros Saques   20000 non-null  int64
 7   % Puntos Ganados con Segundos Saques   20000 non-null  int64
 8   Dobles Faltas                          20000 non-null  int64
 9   Km Recorridos                          20000 non-null  int64
 10  Zonas de Calor                         20000 non-null  object
 11  Puntos de Break                        20000 non-null  int64
 12  Puntos de Oro                          20000 non-null  int64
 13  Errores No Forzados de Fondo de Pista  20000 non-null  int64
 14  Errores No Forzados en Red             20000 non-null  int64
 15  % de Restos Fallados                   20000 non-null  int64
 16  Posición Preferente                    20000 non-null  object
 17  Partido                                20000 non-null  int64
 18  Edad                                   20000 non-null  object
dtypes: int64(16), object(3)
memory usage: 2.9+ MB

In [40]:
import pandas as pd
import numpy as np

# Definimos el número total de IDs
total_ids = 1000

# Creamos la lista de géneros (masculino y femenino)
generos = ['Masculino', 'Femenino']

# Calculamos cuántas veces debemos repetir cada género para obtener 20,000 registros
repeticiones_por_genero = total_ids * 20 // len(generos)

# Repetimos la lista de géneros para igualar la longitud de 20,000 registros
generos_repetidos = np.repeat(generos, repeticiones_por_genero)

# Ajustamos el número total de IDs para que coincida con la longitud de los géneros repetidos
total_ids = len(generos_repetidos)

# Creamos el DataFrame con los IDs y los géneros asignados
df_genero = pd.DataFrame({'Player ID': range(1, total_ids + 1),
                          'Género': generos_repetidos})

# Mostramos el DataFrame resultante
print(df_genero)

       Player ID     Género
0              1  Masculino
1              2  Masculino
2              3  Masculino
3              4  Masculino
4              5  Masculino
...          ...        ...
19995      19996   Femenino
19996      19997   Femenino
19997      19998   Femenino
19998      19999   Femenino
19999      20000   Femenino

[20000 rows x 2 columns]

In [42]:
merged_df = pd.merge(merged_df, df_genero, on='Player ID', how='left')

# Mostramos el resultado del merge
merged_df

,Player ID,Errores No Forzados,Winners,Puntos Ganados de Remate,% Primeros Saques,% Segundos Saques,% Puntos Ganados con Primeros Saques,% Puntos Ganados con Segundos Saques,Dobles Faltas,Km Recorridos,...,Puntos de Break,Puntos de Oro,Errores No Forzados de Fondo de Pista,Errores No Forzados en Red,% de Restos Fallados,Posición Preferente,Partido,Edad,Género_x,Género_y
0,1,48,16,13,0,79,20,86,7,2,...,13,32,18,19,6,D,1,<18,Masculino,Masculino
1,2,29,25,4,88,71,71,92,8,4,...,6,35,47,20,19,R,1,<18,Masculino,Masculino
2,3,44,28,10,65,55,20,4,9,0,...,14,32,21,9,23,D,1,<18,Masculino,Masculino
3,4,5,25,15,29,88,10,41,1,4,...,15,30,48,8,23,R,1,<18,Masculino,Masculino
4,5,16,17,1,2,49,37,6,8,3,...,18,20,14,4,22,D,1,<18,Masculino,Masculino
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,996,27,18,8,100,36,42,46,9,2,...,0,34,9,6,15,D,20,>60,Masculino,Masculino
19996,997,42,18,13,44,98,90,55,7,4,...,17,10,9,5,23,D,20,>60,Masculino,Masculino
19997,998,38,15,13,74,81,49,66,2,1,...,11,34,13,6,21,R,20,>60,Masculino,Masculino
19998,999,15,0,12,66,84,62,1,7,1,...,14,3,17,18,18,D,20,>60,Masculino,Masculino
19999,1000,36,13,7,11,24,40,78,4,2,...,1,15,1,3,12,R,20,>60,Masculino,Masculino

In [44]:
filas = merged_df.iloc[[1, 1001, 2001, 3001]]
filas

,Player ID,Errores No Forzados,Winners,Puntos Ganados de Remate,% Primeros Saques,% Segundos Saques,% Puntos Ganados con Primeros Saques,% Puntos Ganados con Segundos Saques,Dobles Faltas,Km Recorridos,...,Puntos de Break,Puntos de Oro,Errores No Forzados de Fondo de Pista,Errores No Forzados en Red,% de Restos Fallados,Posición Preferente,Partido,Edad,Género_x,Género_y
1,2,29,25,4,88,71,71,92,8,4,...,6,35,47,20,19,R,1,<18,Masculino,Masculino
1001,2,32,4,20,5,36,33,25,8,2,...,11,1,9,18,1,R,2,<18,Masculino,Masculino
2001,2,45,25,8,17,51,73,29,1,4,...,0,0,0,3,18,D,3,<18,Masculino,Masculino
3001,2,44,24,10,72,82,14,26,6,4,...,12,1,50,7,13,D,4,<18,Masculino,Masculino

In [45]:
merged_df = merged_df.drop(columns=['Género_y'], axis = 1)

In [46]:
# Guardar el DataFrame merged_df en un archivo CSV
merged_df.to_csv('merged_data.csv', index=False)