In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
female_18_30 = pd.read_csv('./advanced_female.csv')

In [3]:
female_18_30.head()

,Unnamed: 0,Player ID,Age Group,Gender,Skill Level,Errores No Forzados,Winners,Puntos Ganados de Remate,% Primeros Saques,% Segundos Saques,...,% Puntos Ganados con Segundos Saques,Dobles Faltas,Km Recorridos,Zonas de Calor,Puntos de Break,Puntos de Oro,Errores No Forzados de Fondo de Pista,Errores No Forzados en Red,% de Restos Fallados,Posición Preferente
0,24250,24251,18-30,Female,Advanced,39,13,3,82,95,...,100,5,3,A,18,9,35,9,5,D
1,71282,71283,18-30,Female,Advanced,11,5,15,91,62,...,39,4,1,C,3,8,16,11,19,R
2,17568,17569,18-30,Female,Advanced,8,23,25,89,26,...,82,4,0,A,17,14,29,2,8,R
3,17575,17576,18-30,Female,Advanced,17,20,3,6,31,...,99,9,2,A,9,17,23,17,29,R
4,71263,71264,18-30,Female,Advanced,5,28,8,88,69,...,4,5,0,C,9,16,2,11,29,R

In [4]:
female_18_30.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16704 entries, 0 to 16703
Data columns (total 21 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Unnamed: 0                             16704 non-null  int64
 1   Player ID                              16704 non-null  int64
 2   Age Group                              16704 non-null  object
 3   Gender                                 16704 non-null  object
 4   Skill Level                            16704 non-null  object
 5   Errores No Forzados                    16704 non-null  int64
 6   Winners                                16704 non-null  int64
 7   Puntos Ganados de Remate               16704 non-null  int64
 8   % Primeros Saques                      16704 non-null  int64
 9   % Segundos Saques                      16704 non-null  int64
 10  % Puntos Ganados con Primeros Saques   16704 non-null  int64
 11  % Puntos Ganados con Segundos Saques   16704 non-null  int64
 12  Dobles Faltas                          16704 non-null  int64
 13  Km Recorridos                          16704 non-null  int64
 14  Zonas de Calor                         16704 non-null  object
 15  Puntos de Break                        16704 non-null  int64
 16  Puntos de Oro                          16704 non-null  int64
 17  Errores No Forzados de Fondo de Pista  16704 non-null  int64
 18  Errores No Forzados en Red             16704 non-null  int64
 19  % de Restos Fallados                   16704 non-null  int64
 20  Posición Preferente                    16704 non-null  object
dtypes: int64(16), object(5)
memory usage: 2.7+ MB

In [5]:
female_18_30['Age Group']

0        18-30
1        18-30
2        18-30
3        18-30
4        18-30
         ...
16699      >60
16700      >60
16701      >60
16702      >60
16703      >60
Name: Age Group, Length: 16704, dtype: object

In [8]:
female_18_30 = female_18_30.loc[female_18_30['Age Group'] == '18-30']

In [9]:
female_18_30

,Unnamed: 0,Player ID,Age Group,Gender,Skill Level,Errores No Forzados,Winners,Puntos Ganados de Remate,% Primeros Saques,% Segundos Saques,...,% Puntos Ganados con Segundos Saques,Dobles Faltas,Km Recorridos,Zonas de Calor,Puntos de Break,Puntos de Oro,Errores No Forzados de Fondo de Pista,Errores No Forzados en Red,% de Restos Fallados,Posición Preferente
0,24250,24251,18-30,Female,Advanced,39,13,3,82,95,...,100,5,3,A,18,9,35,9,5,D
1,71282,71283,18-30,Female,Advanced,11,5,15,91,62,...,39,4,1,C,3,8,16,11,19,R
2,17568,17569,18-30,Female,Advanced,8,23,25,89,26,...,82,4,0,A,17,14,29,2,8,R
3,17575,17576,18-30,Female,Advanced,17,20,3,6,31,...,99,9,2,A,9,17,23,17,29,R
4,71263,71264,18-30,Female,Advanced,5,28,8,88,69,...,4,5,0,C,9,16,2,11,29,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3491,54028,54029,18-30,Female,Advanced,12,12,19,39,18,...,9,5,3,C,17,28,45,3,13,R
3492,8142,8143,18-30,Female,Advanced,15,12,11,63,84,...,13,1,1,B,2,14,29,9,22,R
3493,76090,76091,18-30,Female,Advanced,46,5,13,83,37,...,68,10,0,B,11,36,28,13,17,R
3494,77784,77785,18-30,Female,Advanced,35,17,15,17,89,...,82,3,0,A,7,31,16,11,27,R
3495,41651,41652,18-30,Female,Advanced,9,13,9,75,24,...,35,9,0,A,18,33,35,13,22,D

In [10]:
female_18_30 = female_18_30.loc[female_18_30['Errores No Forzados'] <= 20]

In [11]:
female_18_30

,Unnamed: 0,Player ID,Age Group,Gender,Skill Level,Errores No Forzados,Winners,Puntos Ganados de Remate,% Primeros Saques,% Segundos Saques,...,% Puntos Ganados con Segundos Saques,Dobles Faltas,Km Recorridos,Zonas de Calor,Puntos de Break,Puntos de Oro,Errores No Forzados de Fondo de Pista,Errores No Forzados en Red,% de Restos Fallados,Posición Preferente
1,71282,71283,18-30,Female,Advanced,11,5,15,91,62,...,39,4,1,C,3,8,16,11,19,R
2,17568,17569,18-30,Female,Advanced,8,23,25,89,26,...,82,4,0,A,17,14,29,2,8,R
3,17575,17576,18-30,Female,Advanced,17,20,3,6,31,...,99,9,2,A,9,17,23,17,29,R
4,71263,71264,18-30,Female,Advanced,5,28,8,88,69,...,4,5,0,C,9,16,2,11,29,R
7,57613,57614,18-30,Female,Advanced,15,3,23,44,0,...,34,0,2,B,7,0,43,6,25,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3488,98302,98303,18-30,Female,Advanced,16,3,3,23,84,...,87,8,3,B,15,5,25,16,22,R
3490,11600,11601,18-30,Female,Advanced,8,25,8,77,82,...,68,3,4,A,7,24,2,8,9,D
3491,54028,54029,18-30,Female,Advanced,12,12,19,39,18,...,9,5,3,C,17,28,45,3,13,R
3492,8142,8143,18-30,Female,Advanced,15,12,11,63,84,...,13,1,1,B,2,14,29,9,22,R
3495,41651,41652,18-30,Female,Advanced,9,13,9,75,24,...,35,9,0,A,18,33,35,13,22,D

In [12]:
female_18_30 = female_18_30.loc[female_18_30['Puntos Ganados de Remate'] <= 15]
female_18_30

,Unnamed: 0,Player ID,Age Group,Gender,Skill Level,Errores No Forzados,Winners,Puntos Ganados de Remate,% Primeros Saques,% Segundos Saques,...,% Puntos Ganados con Segundos Saques,Dobles Faltas,Km Recorridos,Zonas de Calor,Puntos de Break,Puntos de Oro,Errores No Forzados de Fondo de Pista,Errores No Forzados en Red,% de Restos Fallados,Posición Preferente
1,71282,71283,18-30,Female,Advanced,11,5,15,91,62,...,39,4,1,C,3,8,16,11,19,R
3,17575,17576,18-30,Female,Advanced,17,20,3,6,31,...,99,9,2,A,9,17,23,17,29,R
4,71263,71264,18-30,Female,Advanced,5,28,8,88,69,...,4,5,0,C,9,16,2,11,29,R
8,37332,37333,18-30,Female,Advanced,0,7,11,77,68,...,82,1,4,C,10,23,18,12,18,R
13,37289,37290,18-30,Female,Advanced,11,7,2,53,13,...,74,0,0,B,16,35,34,2,21,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3487,91957,91958,18-30,Female,Advanced,16,9,9,29,77,...,13,3,2,C,11,11,16,16,22,D
3488,98302,98303,18-30,Female,Advanced,16,3,3,23,84,...,87,8,3,B,15,5,25,16,22,R
3490,11600,11601,18-30,Female,Advanced,8,25,8,77,82,...,68,3,4,A,7,24,2,8,9,D
3492,8142,8143,18-30,Female,Advanced,15,12,11,63,84,...,13,1,1,B,2,14,29,9,22,R
3495,41651,41652,18-30,Female,Advanced,9,13,9,75,24,...,35,9,0,A,18,33,35,13,22,D

In [13]:
female_18_30 = female_18_30.loc[female_18_30['Errores No Forzados de Fondo de Pista'] <= 24]
female_18_30

,Unnamed: 0,Player ID,Age Group,Gender,Skill Level,Errores No Forzados,Winners,Puntos Ganados de Remate,% Primeros Saques,% Segundos Saques,...,% Puntos Ganados con Segundos Saques,Dobles Faltas,Km Recorridos,Zonas de Calor,Puntos de Break,Puntos de Oro,Errores No Forzados de Fondo de Pista,Errores No Forzados en Red,% de Restos Fallados,Posición Preferente
1,71282,71283,18-30,Female,Advanced,11,5,15,91,62,...,39,4,1,C,3,8,16,11,19,R
3,17575,17576,18-30,Female,Advanced,17,20,3,6,31,...,99,9,2,A,9,17,23,17,29,R
4,71263,71264,18-30,Female,Advanced,5,28,8,88,69,...,4,5,0,C,9,16,2,11,29,R
8,37332,37333,18-30,Female,Advanced,0,7,11,77,68,...,82,1,4,C,10,23,18,12,18,R
25,96481,96482,18-30,Female,Advanced,2,13,7,71,53,...,43,2,1,B,4,6,23,1,4,R
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3414,90096,90097,18-30,Female,Advanced,17,7,12,29,36,...,24,0,0,C,2,6,21,7,18,D
3419,53226,53227,18-30,Female,Advanced,11,10,6,50,10,...,8,10,0,C,1,6,14,11,25,R
3439,75829,75830,18-30,Female,Advanced,8,23,11,48,12,...,20,7,4,C,10,26,21,8,23,R
3487,91957,91958,18-30,Female,Advanced,16,9,9,29,77,...,13,3,2,C,11,11,16,16,22,D
3490,11600,11601,18-30,Female,Advanced,8,25,8,77,82,...,68,3,4,A,7,24,2,8,9,D

In [14]:
female_18_30.to_csv('female_18_30.csv')